# Generated by Django 3.2.19 on 2023-05-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pessoa_filtro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='filtro',
            new_name='parceiro',
        ),
    ]
